export default {
  elements: [],
  appState: {},
  scrollToContent: true,
  libraryItems: [
    [
      {
        id: "99R9mUoUgLNE7P3UN_RsH",
        type: "rectangle",
        x: 400,
        y: 200,
        width: 140,
        height: 140,
        angle: 0,
        strokeColor: "#000000",
        backgroundColor: "#fab005",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        groupIds: ["anDhR0DIOAoHlvEoTYKcJ"],
        strokeSharpness: "sharp",
        seed: 816766292,
        version: 63,
        versionNonce: 1360739180,
        isDeleted: false,
        boundElementIds: null,
      },
      {
        id: "zfW-T6-Lj3W90Ad1FZzMQ",
        type: "text",
        x: 406,
        y: 204,
        width: 34,
        height: 21,
        angle: 0,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        fillStyle: "hachure",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        groupIds: ["anDhR0DIOAoHlvEoTYKcJ"],
        strokeSharpness: "sharp",
        seed: 366849876,
        version: 55,
        versionNonce: 1306100052,
        isDeleted: false,
        boundElementIds: null,
        text: "note",
        fontSize: 16,
        fontFamily: 1,
        textAlign: "left",
        verticalAlign: "top",
        baseline: 15,
      },
    ],
    [
      {
        type: "rectangle",
        version: 87,
        versionNonce: 1179218796,
        isDeleted: false,
        id: "idSLoZXr4URlKwFoGIxu6",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 571,
        y: 181,
        strokeColor: "#000000",
        backgroundColor: "#e64980",
        width: 140,
        height: 140,
        seed: 116668244,
        groupIds: ["5qdsbbe-LKtW6buJwR6Z7"],
        strokeSharpness: "sharp",
        boundElementIds: [],
      },
      {
        type: "text",
        version: 76,
        versionNonce: 1545495508,
        isDeleted: false,
        id: "aFfzT4YGuX9cFDXUIYSUD",
        fillStyle: "hachure",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 577,
        y: 185,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        width: 34,
        height: 21,
        seed: 990681068,
        groupIds: ["5qdsbbe-LKtW6buJwR6Z7"],
        strokeSharpness: "sharp",
        boundElementIds: [],
        fontSize: 16,
        fontFamily: 1,
        text: "note",
        baseline: 15,
        textAlign: "left",
        verticalAlign: "top",
      },
    ],
    [
      {
        type: "rectangle",
        version: 126,
        versionNonce: 2044041580,
        isDeleted: false,
        id: "8xZvtVEwkEq6BcnKsbulp",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 745,
        y: 188,
        strokeColor: "#000000",
        backgroundColor: "#82c91e",
        width: 140,
        height: 140,
        seed: 1597105876,
        groupIds: ["RUaVBkfdTdMt8OPJMisQo"],
        strokeSharpness: "sharp",
        boundElementIds: [],
      },
      {
        type: "text",
        version: 115,
        versionNonce: 734726228,
        isDeleted: false,
        id: "aiNAgkRYBQdLwXsxR8brj",
        fillStyle: "hachure",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 751,
        y: 192,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        width: 34,
        height: 21,
        seed: 1382260844,
        groupIds: ["RUaVBkfdTdMt8OPJMisQo"],
        strokeSharpness: "sharp",
        boundElementIds: [],
        fontSize: 16,
        fontFamily: 1,
        text: "note",
        baseline: 15,
        textAlign: "left",
        verticalAlign: "top",
      },
    ],
    [
      {
        type: "rectangle",
        version: 156,
        versionNonce: 2112137044,
        isDeleted: false,
        id: "Kd0ieW77eqbYmBcIuFNUO",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 932,
        y: 181,
        strokeColor: "#000000",
        backgroundColor: "#15aabf",
        width: 140,
        height: 140,
        seed: 1690859732,
        groupIds: ["UF6A7jBRPdXH9DJypXCyY"],
        strokeSharpness: "sharp",
        boundElementIds: [],
      },
      {
        type: "text",
        version: 144,
        versionNonce: 1805386196,
        isDeleted: false,
        id: "SE1SPPe2T_iszboamt81B",
        fillStyle: "hachure",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 938,
        y: 185,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        width: 34,
        height: 21,
        seed: 79113836,
        groupIds: ["UF6A7jBRPdXH9DJypXCyY"],
        strokeSharpness: "sharp",
        boundElementIds: [],
        fontSize: 16,
        fontFamily: 1,
        text: "note",
        baseline: 15,
        textAlign: "left",
        verticalAlign: "top",
      },
    ],
    [
      {
        type: "rectangle",
        version: 161,
        versionNonce: 1127260012,
        isDeleted: false,
        id: "LRDf9KHTmLq_0BoU4lhH7",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 1128,
        y: 189,
        strokeColor: "#000000",
        backgroundColor: "#fa5252",
        width: 140,
        height: 140,
        seed: 421139564,
        groupIds: ["1ZBkby8KEOdaVUi6EVD9P"],
        strokeSharpness: "sharp",
        boundElementIds: [],
      },
      {
        type: "text",
        version: 149,
        versionNonce: 1697262572,
        isDeleted: false,
        id: "ROObuP6Y-YpiXm9RkQ3T1",
        fillStyle: "hachure",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 1134,
        y: 193,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        width: 34,
        height: 21,
        seed: 747681876,
        groupIds: ["1ZBkby8KEOdaVUi6EVD9P"],
        strokeSharpness: "sharp",
        boundElementIds: [],
        fontSize: 16,
        fontFamily: 1,
        text: "note",
        baseline: 15,
        textAlign: "left",
        verticalAlign: "top",
      },
    ],
    [
      {
        type: "rectangle",
        version: 145,
        versionNonce: 399460076,
        isDeleted: false,
        id: "FKvSVhYdXuHw6BaQNnPNi",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 1307,
        y: 192,
        strokeColor: "#000000",
        backgroundColor: "#7950f2",
        width: 140,
        height: 140,
        seed: 2060441812,
        groupIds: ["dyKtf_sImfLvrCOTVXyf-"],
        strokeSharpness: "sharp",
        boundElementIds: [],
      },
      {
        type: "text",
        version: 133,
        versionNonce: 1417802068,
        isDeleted: false,
        id: "Ar4gJBxpSccfA2EQqJtFm",
        fillStyle: "hachure",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 1313,
        y: 196,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        width: 34,
        height: 21,
        seed: 1029033580,
        groupIds: ["dyKtf_sImfLvrCOTVXyf-"],
        strokeSharpness: "sharp",
        boundElementIds: [],
        fontSize: 16,
        fontFamily: 1,
        text: "note",
        baseline: 15,
        textAlign: "left",
        verticalAlign: "top",
      },
    ],
    [
      {
        id: "PTIQqOhcVC_JJI-rhQ3ft",
        type: "text",
        x: 603,
        y: 439,
        width: 28,
        height: 32,
        angle: 0,
        strokeColor: "#c92a2a",
        backgroundColor: "#be4bdb",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        groupIds: [],
        strokeSharpness: "sharp",
        seed: 1501305428,
        version: 11,
        versionNonce: 233095380,
        isDeleted: false,
        boundElementIds: null,
        text: "👍",
        fontSize: 28,
        fontFamily: 2,
        textAlign: "left",
        verticalAlign: "top",
        baseline: 25,
      },
    ],
    [
      {
        id: "RXSqpNy1fqscdrIuB3Cy1",
        type: "text",
        x: 662,
        y: 439.5,
        width: 28,
        height: 32,
        angle: 0,
        strokeColor: "#000000",
        backgroundColor: "#be4bdb",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        groupIds: [],
        strokeSharpness: "sharp",
        seed: 1034139348,
        version: 30,
        versionNonce: 863245804,
        isDeleted: false,
        boundElementIds: null,
        text: "👎",
        fontSize: 28,
        fontFamily: 2,
        textAlign: "left",
        verticalAlign: "top",
        baseline: 25,
      },
    ],
    [
      {
        id: "gcdRgpnmM1Zz_mw4ApwXU",
        type: "text",
        x: 720,
        y: 434.5,
        width: 28,
        height: 32,
        angle: 0,
        strokeColor: "#000000",
        backgroundColor: "#be4bdb",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        groupIds: [],
        strokeSharpness: "sharp",
        seed: 1161857772,
        version: 26,
        versionNonce: 461943124,
        isDeleted: false,
        boundElementIds: null,
        text: "⭐",
        fontSize: 28,
        fontFamily: 2,
        textAlign: "left",
        verticalAlign: "top",
        baseline: 25,
      },
    ],
    [
      {
        id: "CPseF84m1YwYlFjSIpxu4",
        type: "text",
        x: 773,
        y: 442.5,
        width: 25,
        height: 32,
        angle: 0,
        strokeColor: "#c92a2a",
        backgroundColor: "#be4bdb",
        fillStyle: "solid",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        groupIds: [],
        strokeSharpness: "sharp",
        seed: 896090836,
        version: 114,
        versionNonce: 582589548,
        isDeleted: false,
        boundElementIds: null,
        text: "❤",
        fontSize: 28,
        fontFamily: 2,
        textAlign: "left",
        verticalAlign: "top",
        baseline: 25,
      },
    ],
  ],
};
